//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restuarant_Managment_System.RS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        internal object Managers;

        public int Id { get; set; }
        public string Uname { get; set; }
        public string Email { get; set; }
        public int Phone { get; set; }
        public int Pasword { get; set; }
    }
}
